grails-app/domain/siteo/administracion/catalogos/TipoColindancia.groovy
package siteo.administracion.catalogos

class TipoColindancia {

    String tipocolindancia
    Boolean estatus
    
    static constraints = {
        tipocolindancia(nullable: false, size: 1..10, blank: false)
    }
    
    static mapping = {
        id generator: 'increment'
    }
    
    String toString(){
        tipocolindancia
    }
}

grails-app/controllers/siteo/administracion/catalogos/TipoColindanciaController.groovy
package siteo.administracion.catalogos



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class TipoColindanciaController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]
    def validaSesionService;

    def index(Integer max) {
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
        params.max = Math.min(max ?: 10, 100)
        params.sort="id"
        params.order="asc"
        respond TipoColindancia.list(params), model:[tipoColindanciaInstanceCount: TipoColindancia.count()]
    }

    def show(TipoColindancia tipoColindanciaInstance) {
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
        respond tipoColindanciaInstance
    }

    def create() {
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
        respond new TipoColindancia(params)
    }

    @Transactional
    def save(TipoColindancia tipoColindanciaInstance) {
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
        if (tipoColindanciaInstance == null) {
            notFound()
            return
        }

        if (tipoColindanciaInstance.hasErrors()) {
            respond tipoColindanciaInstance.errors, view:'create'
            return
        }

        tipoColindanciaInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'tipoColindancia.label', default: 'TipoColindancia'), tipoColindanciaInstance.id])
                redirect tipoColindanciaInstance
            }
            '*' { respond tipoColindanciaInstance, [status: CREATED] }
        }
    }

    def edit(TipoColindancia tipoColindanciaInstance) {
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
        respond tipoColindanciaInstance
    }

    @Transactional
    def update(TipoColindancia tipoColindanciaInstance) {
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
        if (tipoColindanciaInstance == null) {
            notFound()
            return
        }

        if (tipoColindanciaInstance.hasErrors()) {
            respond tipoColindanciaInstance.errors, view:'edit'
            return
        }

        tipoColindanciaInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'TipoColindancia.label', default: 'TipoColindancia'), tipoColindanciaInstance.id])
                redirect tipoColindanciaInstance
            }
            '*'{ respond tipoColindanciaInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(TipoColindancia tipoColindanciaInstance) {
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
        if (tipoColindanciaInstance == null) {
            notFound()
            return
        }

        tipoColindanciaInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'TipoColindancia.label', default: 'TipoColindancia'), tipoColindanciaInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    def cambiaEstatus = {
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
        def tipoCol = TipoColindancia.get(params.idele)
        tipoCol.estatus = !tipoCol.estatus
        tipoCol.save flush:true
        
        redirect(action: 'index')
    }
    
    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'tipoColindancia.label', default: 'TipoColindancia'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/tipoColindancia/_form.gsp
<%@ page import="siteo.administracion.catalogos.TipoColindancia" %>



<div class="fieldcontain ${hasErrors(bean: tipoColindanciaInstance, field: 'tipocolindancia', 'error')} required">
	<label for="tipocolindancia">
		<g:message code="tipoColindancia.tipocolindancia.label" default="Tipo de colindancia" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="tipocolindancia" maxlength="10" required="" value="${tipoColindanciaInstance?.tipocolindancia}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: tipoColindanciaInstance, field: 'estatus', 'error')} ">
	<label for="estatus">
		<g:message code="tipoColindancia.estatus.label" default="Estatus" />
		
	</label>
	<g:checkBox name="estatus" value="${tipoColindanciaInstance?.estatus}" />

</div>

grails-app/views/tipoColindancia/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'tipoColindancia.label', default: 'TipoColindancia')}" />
		<title><g:message code="Nuevo" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-tipoColindancia" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="Lista" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-tipoColindancia" class="content scaffold-create" role="main">
			<h1><g:message code="Nuevo" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${tipoColindanciaInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${tipoColindanciaInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:tipoColindanciaInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/tipoColindancia/edit.gsp
<%@ page import="siteo.administracion.catalogos.TipoColindancia" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'tipoColindancia.label', default: 'TipoColindancia')}" />
		<title><g:message code="Editar" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-tipoColindancia" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="Lista" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="Nuevo" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-tipoColindancia" class="content scaffold-edit" role="main">
			<h1><g:message code="Editar" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${tipoColindanciaInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${tipoColindanciaInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:tipoColindanciaInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${tipoColindanciaInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/tipoColindancia/index.gsp
<%@ page import="siteo.administracion.catalogos.TipoColindancia" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'tipoColindancia.label', default: 'TipoColindancia')}" />
		<title><g:message code="Lista" args="[entityName]" /></title>
	</head>
	<body>
            <g:form name="festatus" controller="TipoColindancia" action="cambiaEstatus">
                <input id="idele" name="idele" type="hidden" value=""/>
            </g:form>
		<a href="#list-tipoColindancia" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="Nuevo" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-tipoColindancia" class="content scaffold-list" role="main">
			<h1><g:message code="Lista" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="tipocolindancia" title="${message(code: 'tipoColindancia.tipocolindancia.label', default: 'Tipo de colindancia')}" />
					
						<g:sortableColumn property="estatus" title="${message(code: 'tipoColindancia.estatus.label', default: 'Estatus')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${tipoColindanciaInstanceList}" status="i" var="tipoColindanciaInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="edit" id="${tipoColindanciaInstance.id}">${fieldValue(bean: tipoColindanciaInstance, field: "tipocolindancia")}</g:link></td>
					
						<td><g:formatBoolean boolean="${tipoColindanciaInstance.estatus}" true="ACTIVO" false="BAJA"/>
                                                    <a href="javascript: CambiaEstatus('${tipoColindanciaInstance.id}')" title="Cambiar Estatus">
                                                        <img src="${assetPath(src: '/skin/switch.png')}" width="20" height="20"/>
                                                    </a></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${tipoColindanciaInstanceCount ?: 0}" />
			</div>
                        <script>
                            function CambiaEstatus(id){
                                var idele = document.getElementById('idele');
                                idele.value = id;
                                var frm = document.getElementById('festatus');
                                frm.submit();
                            }
                        </script>
		</div>
	</body>
</html>

grails-app/views/tipoColindancia/show.gsp
<%@ page import="siteo.administracion.catalogos.TipoColindancia" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'tipoColindancia.label', default: 'TipoColindancia')}" />
		<title><g:message code="Tipo colindancia" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-tipoColindancia" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="Lista" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="Nuevo" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-tipoColindancia" class="content scaffold-show" role="main">
			<h1><g:message code="Tipo colindancia" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list tipoColindancia">
			
				<g:if test="${tipoColindanciaInstance?.tipocolindancia}">
				<li class="fieldcontain">
					<span id="tipocolindancia-label" class="property-label"><g:message code="tipoColindancia.tipocolindancia.label" default="Tipo de colindancia" /></span>
					
						<span class="property-value" aria-labelledby="tipocolindancia-label"><g:fieldValue bean="${tipoColindanciaInstance}" field="tipocolindancia"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${tipoColindanciaInstance?.estatus}">
				<li class="fieldcontain">
					<span id="estatus-label" class="property-label"><g:message code="tipoColindancia.estatus.label" default="Estatus" /></span>
					
						<span class="property-value" aria-labelledby="estatus-label"><g:formatBoolean boolean="${tipoColindanciaInstance?.estatus}" true="ACTIVO" false="BAJA" /></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:tipoColindanciaInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${tipoColindanciaInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>