grails-app/domain/siteo/seguridad/Usuario.groovy
package siteo.seguridad
import siteo.administracion.catalogos.Notario

class Usuario {
    String titulo
    String nombre
    String usuario
    String ubicacion
    String passwd
    Boolean estatus
    Boolean firma
    
    static hasMany = [notarias:Notario, roles:Roles]

    static constraints = {
        ubicacion(nullable:true, blank:true)
        usuario(unique:true, minSize:6)
        titulo(blank:true, nullable:true)
        firma(nullable:true)
    }
    
    static mapping = {
        id generator: 'increment'
    }
    
    String toString(){
        String usuario = nombre
        if (titulo)
            usuario = titulo+" "+nombre
        usuario
    }
}

grails-app/controllers/siteo/seguridad/UsuarioController.groovy
package siteo.seguridad



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional
import siteo.administracion.catalogos.Notario

@Transactional(readOnly = true)
class UsuarioController {
    
    def usuarioService
    def validaSesionService
    def bitacoraService
    
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    @Transactional
    def login(){
        session.user = null
        session.random = new Random()
        if(params){
            
            if (!usuarioService.valida(params)){
                flash.message = "Usuario no existe o está dado de baja"
                redirect(controller:'login', action:'index')
                return;
            }else{
                def us = usuarioService.obtenerPorUsuarioYPass(params);  //Consulta el usuario mediante el login y contraseña enviados
                def totRol = usuarioService.totalRoles(us)
                def totNot = usuarioService.totalNotario(us);    //Consulta el total de roles activos que tiene el usuario
                session.setAttribute("usuario", us);
                session.user = us.id
                if(!us.titulo){
                    session.nombrecompleto = us.nombre
                }else{
                    session.nombrecompleto = us.titulo + " " + us.nombre
                }
                session.nombrenot = null;
                session.nombrerol = null;
                session.setAttribute("numNot",totNot);
                session.setAttribute("numRol",totRol)
                bitacoraService.registraActividad(us, "ACCESO AL SISTEMA", null);
                if(totRol ==1){
                    def r = usuarioService.rolActivo(us)
                    def rolActual = usuarioService.nombreRol(r)
                    if(rolActual == "ADMINISTRADOR"){
                        session.nombrerol = rolActual
                        session.setAttribute("menu", usuarioService.menu(r))
                        session.setAttribute("idrol", r)
                        redirect(controller:'menu', action:'index')
                    }                        
                    else if(totNot ==1){
                        def notActual = usuarioService.notarioActivo(us);
                        def nomNot = usuarioService.nombreNotario(notActual);
                        session.nombrerol = rolActual
                        session.nombrenot = nomNot
                        session.auxidnot = notActual
                        session.setAttribute("menu", usuarioService.menu(r))
                        session.setAttribute("idrol", r)
                        redirect(controller:'menu', action:'index')
                    }else if (totNot >1){
                        def nomRol = usuarioService.nombreRol(r)
                        session.nombrerol = nomRol
                        session.setAttribute("idrol", r)
                        redirect(controller:'usuario', action:'seleccionaNot',id:us.id)
                        
                    }
                }else if(totRol > 1){
                    flash.message= "Seleccione el rol a utilizar"
                    redirect(controller:'usuario', action:'seleccionaRol', id:us.id)
                }else{
                    flash.message="No tiene asociados roles"
                    redirect(controller:'usuario',action:'logout')
                }
            }
        }else{
            redirect(controller:"login",action:"index");
        }
    }
    
    def logout = {
        session.invalidate()
        redirect(controller:'login', action: "index")
    }
    
    def seleccionaRol(){
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
        }
        session.nombrerol = null
        session.nombrenot = null;
        def user = Usuario.findById(params.id)
        def rol = user.roles.id
        def rRol = Roles.findAllByEstatusAndIdInList("true",rol, [sort:'rol'])
        [user:user,roles:rRol]
    }
    
    def rolSelec(){
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
        }
        def r = Roles.findById(params.rol)
        session.idrol = r.id
        def nomRol = usuarioService.nombreRol(r.id)
        def us = Usuario.findById(session.user)
        def totNot = usuarioService.totalNotario(us); 
        session.nombrerol = nomRol
        if(nomRol == "ADMINISTRADOR"){
            session.setAttribute("menu", usuarioService.menu(r.id))
            redirect(controller:'menu', action:'index')
        }else{
            if(totNot==1){
                def notActual = usuarioService.notarioActivo(us);
                def nomNot = usuarioService.nombreNotario(notActual);
                session.nombrenot = nomNot
                session.auxidnot=notActual
                session.setAttribute("menu", usuarioService.menu(r.id))
                redirect(controller:'menu', action:'index')
            }else if(totNot > 1){
                redirect(controller:'usuario', action:'seleccionaNot', id:us.id)
            }
        }
    }
    def seleccionaNot(){
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return
        }
        session.nombrenot = null
        def user = Usuario.findById(params.id)
        def not = user.notarias.id
        def rNot = Notario.findAllByEstatusAndIdInList("true",not, [sort:'notaria'])
        [user:user,roles:rNot]
    }
    
    def notSelec(){
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return
        }
        
        def n = Notario.findById(params.nota)
        def nomNot = usuarioService.nombreNotario(n.id)
        session.nombrenot = nomNot
        session.auxidnot = n.id
        session.setAttribute("menu", usuarioService.menu(session.idrol))
        redirect(controller:'menu', action:'index')
    }
    
    def cambiaEstatus = {
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
        if(!validaSesionService.compruebaRol(session,"ADMINISTRADOR")){
            redirect(controller:'menu', action:'index')
        }
        def instancia = Usuario.get(params.idele)
        instancia.estatus = !instancia.estatus
        instancia.save flush:true
        
        redirect(action: 'index')
    }
    
    def passwd(){
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
    }
    @Transactional
    def modificapwd(){
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
        }
        def x = usuarioService.cambiaPass(params, session)
        flash.message= x
        if(x == "Contraseña modificada correctamente"){
            def usActual = Usuario.findById(session.user)
            bitacoraService.registraActividad(usActual, "MODIFICA CONTRASEÑA", session.user)
        }
        redirect(action:"passwd")
    }
    
    def index(Integer max) {
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
        if(!validaSesionService.compruebaRol(session,"ADMINISTRADOR")){
            redirect(controller:'menu', action:'index')
        }
        params.max = Math.min(max ?: 10, 100)
        params.sort = "nombre"
        params.order ="asc"
        respond Usuario.list(params), model:[usuarioInstanceCount: Usuario.count()]
    }

    def show(Usuario usuarioInstance) {
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
        if(!validaSesionService.compruebaRol(session,"ADMINISTRADOR")){
            redirect(controller:'menu', action:'index')
        }
        respond usuarioInstance
    }

    def create() {
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
        if(!validaSesionService.compruebaRol(session,"ADMINISTRADOR")){
            redirect(controller:'menu', action:'index')
        }
        respond new Usuario(params)
    }

    @Transactional
    def save(Usuario usuarioInstance) {
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
        if(!validaSesionService.compruebaRol(session,"ADMINISTRADOR")){
            redirect(controller:'menu', action:'index')
        }
        if (usuarioInstance == null) {
            notFound()
            return
        }

        if (usuarioInstance.hasErrors()) {
            respond usuarioInstance.errors, view:'create'
            return
        }

        usuarioInstance.passwd = usuarioInstance.passwd.encodeAsSHA1()
        usuarioInstance.save flush:true
        
        def usActual = Usuario.findById(session.user)
        bitacoraService.registraActividad(usActual, "CREA USUARIO", usuarioInstance.id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'usuario.label', default: 'Usuario'), usuarioInstance.id])
                redirect usuarioInstance
            }
            '*' { respond usuarioInstance, [status: CREATED] }
        }
    }

    def edit(Usuario usuarioInstance) {
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
        if(!validaSesionService.compruebaRol(session,"ADMINISTRADOR")){
            redirect(controller:'menu', action:'index')
        }
        respond usuarioInstance
    }

grails-app/views/usuario/_form.gsp
<%@ page import="siteo.seguridad.Usuario" %>



<div class="fieldcontain ${hasErrors(bean: usuarioInstance, field: 'titulo', 'error')} ">
	<label for="titulo">
		<g:message code="usuario.titulo.label" default="Titulo" />
		
	</label>
	<g:textField name="titulo" value="${usuarioInstance?.titulo}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: usuarioInstance, field: 'nombre', 'error')} required">
	<label for="nombre">
		<g:message code="usuario.nombre.label" default="Nombre" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="nombre" required="" value="${usuarioInstance?.nombre}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: usuarioInstance, field: 'usuario', 'error')} required">
	<label for="usuario">
		<g:message code="usuario.usuario.label" default="Usuario" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="usuario" required="" value="${usuarioInstance?.usuario}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: usuarioInstance, field: 'passwd', 'error')} required">
	<label for="passwd">
		<g:message code="usuario.passwd.label" default="Contraseña" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="passwd" required="" value="${usuarioInstance?.passwd}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: usuarioInstance, field: 'ubicacion', 'error')} ">
	<label for="ubicacion">
		<g:message code="usuario.ubicacion.label" default="Ubicacion" />
		
	</label>
	<g:textField name="ubicacion" value="${usuarioInstance?.ubicacion}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: usuarioInstance, field: 'estatus', 'error')} ">
	<label for="estatus">
		<g:message code="usuario.estatus.label" default="Estatus" />
		
	</label>
	<g:checkBox name="estatus" value="${usuarioInstance?.estatus}" />

</div>

<div class="fieldcontain ${hasErrors(bean: usuarioInstance, field: 'roles', 'error')} ">
	<label for="roles">
		<g:message code="usuario.roles.label" default="Roles" />
		
	</label>
	<g:select name="roles" from="${siteo.seguridad.Roles.list(sort: "rol", order: "asc")}" multiple="multiple" optionKey="id" size="5" value="${usuarioInstance?.roles*.id}" class="many-to-many"/>

</div>

<div class="fieldcontain ${hasErrors(bean: usuarioInstance, field: 'notarias', 'error')} ">
	<label for="notarias">
		<g:message code="usuario.notarias.label" default="Notarias" />
		
	</label>
	<g:select name="notarias" from="${siteo.administracion.catalogos.Notario.list(sort: "notaria", order: "asc")}" multiple="multiple" optionKey="id" size="5" value="${usuarioInstance?.notarias*.id}" class="many-to-many"/>

</div>
<div class="fieldcontain ${hasErrors(bean: usuarioInstance, field: 'firma', 'error')} ">
	<label for="firma">
		<g:message code="usuario.firma.label" default="Firma" />
		
	</label>
	<g:checkBox name="firma" value="${usuarioInstance?.estatus}" />

</div>

grails-app/views/usuario/_formEdit.gsp
<%@ page import="siteo.seguridad.Usuario" %>



<div class="fieldcontain ${hasErrors(bean: usuarioInstance, field: 'titulo', 'error')} ">
	<label for="titulo">
		<g:message code="usuario.titulo.label" default="Titulo" />
		
	</label>
	<g:textField name="titulo" value="${usuarioInstance?.titulo}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: usuarioInstance, field: 'nombre', 'error')} required">
	<label for="nombre">
		<g:message code="usuario.nombre.label" default="Nombre" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="nombre" required="" value="${usuarioInstance?.nombre}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: usuarioInstance, field: 'usuario', 'error')} required">
	<label for="usuario">
		<g:message code="usuario.usuario.label" default="Usuario" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="usuario" required="" value="${usuarioInstance?.usuario}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: usuarioInstance, field: 'ubicacion', 'error')} ">
	<label for="ubicacion">
		<g:message code="usuario.ubicacion.label" default="Ubicacion" />
		
	</label>
	<g:textField name="ubicacion" value="${usuarioInstance?.ubicacion}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: usuarioInstance, field: 'estatus', 'error')} ">
	<label for="estatus">
		<g:message code="usuario.estatus.label" default="Estatus" />
		
	</label>
	<g:checkBox name="estatus" value="${usuarioInstance?.estatus}" />

</div>

<div class="fieldcontain ${hasErrors(bean: usuarioInstance, field: 'roles', 'error')} ">
	<label for="roles">
		<g:message code="usuario.roles.label" default="Roles" />
		
	</label>
	<g:select name="roles" from="${siteo.seguridad.Roles.list(sort: "rol", order: "asc")}" multiple="multiple" optionKey="id" size="5" value="${usuarioInstance?.roles*.id}" class="many-to-many"/>

</div>

<div class="fieldcontain ${hasErrors(bean: usuarioInstance, field: 'notarias', 'error')} ">
	<label for="notarias">
		<g:message code="usuario.notarias.label" default="Notarias" />
		
	</label>
	<g:select name="notarias" from="${siteo.administracion.catalogos.Notario.list(sort: "notaria", order: "asc")}" multiple="multiple" optionKey="id" size="5" value="${usuarioInstance?.notarias*.id}" class="many-to-many"/>

</div>

<div class="fieldcontain ${hasErrors(bean: usuarioInstance, field: 'firma', 'error')} ">
	<label for="firma">
		<g:message code="usuario.firma.label" default="Firma" />
		
	</label>
	<g:checkBox name="firma" value="${usuarioInstance?.firma}" />
</div>

grails-app/views/usuario/buscar.gsp

<%@ page import="siteo.seguridad.Usuario" %>

<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" />
		<title>Busqueda</title>
	</head>
	<body>
		<a href="#list-usuario" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}">Principal</a></li>
				<li><g:link class="list" action="index">Lista</g:link></li>
				<li><g:link class="create" action="create">Nuevo</g:link></li>
			</ul>
		</div>
		<div id="list-usuario" class="content scaffold-list" role="main">
			<h1>Resultado de la busqueda</h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
                        <table>
                            <tr>
                                <th><g:form action="buscar">
                                    Usuario:
                                    <g:textField name="criterio" required="" autofocus="" />
                                    <g:submitButton name="Buscar" action="buscar" value="Buscar"/>
                                    </g:form>
                                </th>
                                
                            </tr>
                        </table>
			<table>
			<thead>
					<tr>
						<g:sortableColumn property="nombre" title="${message(code: 'usuario.nombre.label', default: 'Nombre')}" />
                                                
                                                <g:sortableColumn property="usuario" title="${message(code: 'usuario.usuario.label', default: 'Usuario')}" />
					
						<g:sortableColumn property="estatus" title="${message(code: 'usuario.estatus.label', default: 'Estatus')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${usuarioInstanceList}" status="i" var="usuarioInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="edit" id="${usuarioInstance.id}">${fieldValue(bean: usuarioInstance, field: "nombre")}</g:link></td>
					
						<td>${fieldValue(bean: usuarioInstance, field: "usuario")}</td>
					
						<td><g:formatBoolean true="ACTIVO" false="BAJA" boolean="${usuarioInstance.estatus}" />
                                                    <a href="javascript: CambiaEstatus('${usuarioInstance.id}')" title="Cambiar Estatus">
                                                        <img src="${assetPath(src: '/skin/switch.png')}" width="20" height="20"/>
                                                    </a>
                                                </td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${usuarioInstanceCount ?: 0}" />
			</div>
                        <script>
                            function CambiaEstatus(id){
                                var idele = document.getElementById('idele');
                                idele.value = id;
                                var frm = document.getElementById('festatus');
                                frm.submit();
                            }
                        </script>
                        <g:form name="festatus" controller="Usuario" action="cambiaEstatus">
                            <input id="idele" name="idele" type="hidden" value=""/>
                        </g:form>
		</div>
	</body>
</html>

grails-app/views/usuario/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" />
		<title><g:message code="Nuevo Usuario" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-usuario" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="Lista" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-usuario" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${usuarioInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${usuarioInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:usuarioInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/usuario/edit.gsp
<%@ page import="siteo.seguridad.Usuario" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-usuario" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="Lista" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="Nuevo" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-usuario" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${usuarioInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${usuarioInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:usuarioInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${usuarioInstance?.version}" />
				<fieldset class="form">
					<g:render template="formEdit"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                                        <g:field type="button" value="Reset Contraseña" name="contraseña" onClick="resetPass()" />
				</fieldset>
			</g:form>
		</div>
                <div id="dialog-pass" title="Cambiar Contraseña">
                    <p id="agregaMensaje" class="error">Nueva Contraseña</p>
                    Nueva:<g:field type="password" name="pass1" required=""/> <br/>
                    Repita:<g:field type="password" name="pass2" required=""/>
                    <br/>
                </div>
                <script function="javascript">
                    function resetPass(){
                        $( "#dialog-pass" ).dialog( "open" );
                    }
                    $(function() {
                        $( "#dialog-pass" ).dialog({
                        resizable: false,
                        width:300,
                        height:230,
                        modal: true,
                        autoOpen: false,
                        buttons: {
                            "Aceptar": function() {
                                if($("#pass1").val() !=""){
                                    if($("#pass2").val() != ""){
                                        if($("#pass1").val() == $("#pass2").val()){
                                               mandaPass();
                                                $( this ).dialog( "close" );
                                        }
                                        else{
                                            $("#pass1").val("");
                                            $("#pass2").val("");
                                            $("#pass1").focus();
                                        }
                                    }
                                    else{
                                        $("#pass2").focus();
                                    }
                                }else{
                                    $("#pass1").focus();
                                }
                            },
                            "Cancelar": function() {
                                $( this ).dialog( "close" );
                            }
                        }
                        });
                    });
                    function mandaPass(){
                        $.post("../resetPass", {usuario:${usuarioInstance.id}, pass:$("#pass1").val() }, function(){
                            MostrarMensaje("Contraseña modificada")
                        })
                        $("#pass1").val("");
                        $("#pass2").val("");
                    }
                    </script>
	</body>
</html>

grails-app/views/usuario/index.gsp
<%@ page import="siteo.seguridad.Usuario" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-usuario" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="Nuevo" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-usuario" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
                        <table>
                            <tr>
                                <th><g:form action="buscar">
                                    Usuario:
                                    <g:textField name="criterio" required="" autofocus="" />
                                    <g:submitButton name="Buscar" action="buscar" value="Buscar"/>
                                    </g:form>
                                </th>
                            </tr>
                        </table>
			<table>
			<thead>
					<tr>
						<g:sortableColumn property="nombre" title="${message(code: 'usuario.nombre.label', default: 'Nombre')}" />
                                                
                                                <g:sortableColumn property="usuario" title="${message(code: 'usuario.usuario.label', default: 'Usuario')}" />
					
						<g:sortableColumn property="estatus" title="${message(code: 'usuario.estatus.label', default: 'Estatus')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${usuarioInstanceList}" status="i" var="usuarioInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="edit" id="${usuarioInstance.id}">${fieldValue(bean: usuarioInstance, field: "nombre")}</g:link></td>
					
						<td>${fieldValue(bean: usuarioInstance, field: "usuario")}</td>
					
						<td><g:formatBoolean true="ACTIVO" false="BAJA" boolean="${usuarioInstance.estatus}" />
                                                    <a href="javascript: CambiaEstatus('${usuarioInstance.id}')" title="Cambiar Estatus">
                                                        <img src="${assetPath(src: '/skin/switch.png')}" width="20" height="20"/>
                                                    </a>
                                                </td>
                                                
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${usuarioInstanceCount ?: 0}" />
			</div>
                        <script>
                            function CambiaEstatus(id){
                                var idele = document.getElementById('idele');
                                idele.value = id;
                                var frm = document.getElementById('festatus');
                                frm.submit();
                            }
                        </script>
                        <g:form name="festatus" controller="Usuario" action="cambiaEstatus">
                            <input id="idele" name="idele" type="hidden" value=""/>
                        </g:form>
		</div>
	</body>
</html>