grails-app/domain/siteo/administracion/catalogos/TipoPersona.groovy
package siteo.administracion.catalogos

class TipoPersona {

    String tipopersona
    Boolean estatus
    
    static constraints = {
        tipopersona (nullable: false, size:1..10, blank:false)
    }
    
    static mapping = {
        id generator: 'increment'
    }
    
    String toString(){
        tipopersona
    }
}

grails-app/controllers/siteo/administracion/catalogos/TipoPersonaController.groovy
package siteo.administracion.catalogos



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class TipoPersonaController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]
    def validaSesionService;
    
    def index(Integer max) {
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
        params.max = Math.min(max ?: 10, 100)
        params.sort="id"
        params.order="asc"
        respond TipoPersona.list(params), model:[tipoPersonaInstanceCount: TipoPersona.count()]
    }

    def show(TipoPersona tipoPersonaInstance) {
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
        respond tipoPersonaInstance
    }

    def create() {
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
        respond new TipoPersona(params)
    }

    @Transactional
    def save(TipoPersona tipoPersonaInstance) {
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
        if (tipoPersonaInstance == null) {
            notFound()
            return
        }

        if (tipoPersonaInstance.hasErrors()) {
            respond tipoPersonaInstance.errors, view:'create'
            return
        }

        tipoPersonaInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'tipoPersona.label', default: 'TipoPersona'), tipoPersonaInstance.id])
                redirect tipoPersonaInstance
            }
            '*' { respond tipoPersonaInstance, [status: CREATED] }
        }
    }

    def edit(TipoPersona tipoPersonaInstance) {
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
        respond tipoPersonaInstance
    }

    @Transactional
    def update(TipoPersona tipoPersonaInstance) {
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
        if (tipoPersonaInstance == null) {
            notFound()
            return
        }

        if (tipoPersonaInstance.hasErrors()) {
            respond tipoPersonaInstance.errors, view:'edit'
            return
        }

        tipoPersonaInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'TipoPersona.label', default: 'TipoPersona'), tipoPersonaInstance.id])
                redirect tipoPersonaInstance
            }
            '*'{ respond tipoPersonaInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(TipoPersona tipoPersonaInstance) {
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
        if (tipoPersonaInstance == null) {
            notFound()
            return
        }

        tipoPersonaInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'TipoPersona.label', default: 'TipoPersona'), tipoPersonaInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    def cambiaEstatus = {
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
        def tipoPer = TipoPersona.get(params.idele)
        tipoPer.estatus = !tipoPer.estatus
        tipoPer.save flush:true
        
        redirect(action: 'index')
    }
    
    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'tipoPersona.label', default: 'TipoPersona'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/tipoPersona/_form.gsp
<%@ page import="siteo.administracion.catalogos.TipoPersona" %>



<div class="fieldcontain ${hasErrors(bean: tipoPersonaInstance, field: 'tipopersona', 'error')} required">
	<label for="tipopersona">
		<g:message code="tipoPersona.tipopersona.label" default="Tipo de persona" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="tipopersona" maxlength="10" required="" value="${tipoPersonaInstance?.tipopersona}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: tipoPersonaInstance, field: 'estatus', 'error')} ">
	<label for="estatus">
		<g:message code="tipoPersona.estatus.label" default="Estatus" />
		
	</label>
	<g:checkBox name="estatus" value="${tipoPersonaInstance?.estatus}" />

</div>

grails-app/views/tipoPersona/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'tipoPersona.label', default: 'TipoPersona')}" />
		<title><g:message code="Nuevo" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-tipoPersona" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="Lista" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-tipoPersona" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${tipoPersonaInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${tipoPersonaInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:tipoPersonaInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/tipoPersona/edit.gsp
<%@ page import="siteo.administracion.catalogos.TipoPersona" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'tipoPersona.label', default: 'TipoPersona')}" />
		<title><g:message code="Editar" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-tipoPersona" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="Lista" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="Nuevo" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-tipoPersona" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${tipoPersonaInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${tipoPersonaInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:tipoPersonaInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${tipoPersonaInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/tipoPersona/index.gsp
<%@ page import="siteo.administracion.catalogos.TipoPersona" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'tipoPersona.label', default: 'TipoPersona')}" />
		<title><g:message code="Lista" args="[entityName]" /></title>
	</head>
	<body>
            <g:form name="festatus" controller="TipoPersona" action="cambiaEstatus">
                <input id="idele" name="idele" type="hidden" value=""/>
            </g:form>
		<a href="#list-tipoPersona" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="Nuevo" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-tipoPersona" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="tipopersona" title="${message(code: 'tipoPersona.tipopersona.label', default: 'Tipo de persona')}" />
					
						<g:sortableColumn property="estatus" title="${message(code: 'tipoPersona.estatus.label', default: 'Estatus')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${tipoPersonaInstanceList}" status="i" var="tipoPersonaInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="edit" id="${tipoPersonaInstance.id}">${fieldValue(bean: tipoPersonaInstance, field: "tipopersona")}</g:link></td>
					
						<td><g:formatBoolean boolean="${tipoPersonaInstance.estatus}" true="ACTIVO" false="BAJA" />
                                                    <a href="javascript: CambiaEstatus('${tipoPersonaInstance.id}')" title="Cambiar Estatus">
                                                        <img src="${assetPath(src: '/skin/switch.png')}" width="20" height="20"/>
                                                    </a></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${tipoPersonaInstanceCount ?: 0}" />
			</div>
                        <script>
                            function CambiaEstatus(id){
                                var idele = document.getElementById('idele');
                                idele.value = id;
                                var frm = document.getElementById('festatus');
                                frm.submit();
                            }
                        </script>
		</div>
	</body>
</html>

grails-app/views/tipoPersona/show.gsp
<%@ page import="siteo.administracion.catalogos.TipoPersona" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'tipoPersona.label', default: 'TipoPersona')}" />
		<title><g:message code="Tipo de persona" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-tipoPersona" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="Lista" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="Nuevo" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-tipoPersona" class="content scaffold-show" role="main">
			<h1><g:message code="Tipo de persona" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list tipoPersona">
			
				<g:if test="${tipoPersonaInstance?.tipopersona}">
				<li class="fieldcontain">
					<span id="tipopersona-label" class="property-label"><g:message code="tipoPersona.tipopersona.label" default="Tipo de persona" /></span>
					
						<span class="property-value" aria-labelledby="tipopersona-label"><g:fieldValue bean="${tipoPersonaInstance}" field="tipopersona"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${tipoPersonaInstance?.estatus}">
				<li class="fieldcontain">
					<span id="estatus-label" class="property-label"><g:message code="tipoPersona.estatus.label" default="Estatus" /></span>
					
						<span class="property-value" aria-labelledby="estatus-label"><g:formatBoolean boolean="${tipoPersonaInstance?.estatus}" true="ACTIVO" false="BAJA" /></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:tipoPersonaInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${tipoPersonaInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>