grails-app/domain/siteo/administracion/catalogos/TipoPropietario.groovy
package siteo.administracion.catalogos

class TipoPropietario {
    
    String tipopropietario
    Boolean estatus

    static constraints = {
        tipopropietario(nullable: false, size:1..15, blank: false)
    }
    
    static mapping = {
        id generator: 'increment'
    }
    
    String toString(){
        tipopropietario
    }
}

grails-app/controllers/siteo/administracion/catalogos/TipoPropietarioController.groovy
package siteo.administracion.catalogos



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class TipoPropietarioController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]
    def validaSesionService;
    
    def index(Integer max) {
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
        params.sort="id"
        params.order="asc"
        params.max = Math.min(max ?: 10, 100)
        respond TipoPropietario.list(params), model:[tipoPropietarioInstanceCount: TipoPropietario.count()]
    }

    def show(TipoPropietario tipoPropietarioInstance) {
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
        respond tipoPropietarioInstance
    }

    def create() {
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
        respond new TipoPropietario(params)
    }

    @Transactional
    def save(TipoPropietario tipoPropietarioInstance) {
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
        if (tipoPropietarioInstance == null) {
            notFound()
            return
        }

        if (tipoPropietarioInstance.hasErrors()) {
            respond tipoPropietarioInstance.errors, view:'create'
            return
        }

        tipoPropietarioInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'tipoPropietario.label', default: 'TipoPropietario'), tipoPropietarioInstance.id])
                redirect tipoPropietarioInstance
            }
            '*' { respond tipoPropietarioInstance, [status: CREATED] }
        }
    }

    def edit(TipoPropietario tipoPropietarioInstance) {
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
        respond tipoPropietarioInstance
    }

    @Transactional
    def update(TipoPropietario tipoPropietarioInstance) {
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
        if (tipoPropietarioInstance == null) {
            notFound()
            return
        }

        if (tipoPropietarioInstance.hasErrors()) {
            respond tipoPropietarioInstance.errors, view:'edit'
            return
        }

        tipoPropietarioInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'TipoPropietario.label', default: 'TipoPropietario'), tipoPropietarioInstance.id])
                redirect tipoPropietarioInstance
            }
            '*'{ respond tipoPropietarioInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(TipoPropietario tipoPropietarioInstance) {
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
        if (tipoPropietarioInstance == null) {
            notFound()
            return
        }

        tipoPropietarioInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'TipoPropietario.label', default: 'TipoPropietario'), tipoPropietarioInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    def cambiaEstatus = {
        if (!validaSesionService.sesionActiva(session)){
            redirect(controller:'Usuario', action:'logout')
            return;
        }
        def tipoProp = TipoPropietario.get(params.idele)
        tipoProp.estatus = !tipoProp.estatus
        tipoProp.save flush:true
        
        redirect(action: 'index')
    }
    
    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'tipoPropietario.label', default: 'TipoPropietario'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/tipoPropietario/_form.gsp
<%@ page import="siteo.administracion.catalogos.TipoPropietario" %>



<div class="fieldcontain ${hasErrors(bean: tipoPropietarioInstance, field: 'tipopropietario', 'error')} required">
	<label for="tipopropietario">
		<g:message code="tipoPropietario.tipopropietario.label" default="Tipo de propietario" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="tipopropietario" maxlength="15" required="" value="${tipoPropietarioInstance?.tipopropietario}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: tipoPropietarioInstance, field: 'estatus', 'error')} ">
	<label for="estatus">
		<g:message code="tipoPropietario.estatus.label" default="Estatus" />
		
	</label>
	<g:checkBox name="estatus" value="${tipoPropietarioInstance?.estatus}" />

</div>

grails-app/views/tipoPropietario/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'tipoPropietario.label', default: 'TipoPropietario')}" />
		<title><g:message code="Nuevo" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-tipoPropietario" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="Lista" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-tipoPropietario" class="content scaffold-create" role="main">
			<h1><g:message code="Nuevo" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${tipoPropietarioInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${tipoPropietarioInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:tipoPropietarioInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/tipoPropietario/edit.gsp
<%@ page import="siteo.administracion.catalogos.TipoPropietario" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'tipoPropietario.label', default: 'TipoPropietario')}" />
		<title><g:message code="Editar" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-tipoPropietario" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="Lista" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="Nuevo" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-tipoPropietario" class="content scaffold-edit" role="main">
			<h1><g:message code="Editar" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${tipoPropietarioInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${tipoPropietarioInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:tipoPropietarioInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${tipoPropietarioInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/tipoPropietario/index.gsp
<%@ page import="siteo.administracion.catalogos.TipoPropietario" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'tipoPropietario.label', default: 'TipoPropietario')}" />
		<title><g:message code="Lista" args="[entityName]" /></title>
	</head>
	<body>
            <g:form name="festatus" controller="TipoPropietario" action="cambiaEstatus">
                <input id="idele" name="idele" type="hidden" value=""/>
            </g:form>
		<a href="#list-tipoPropietario" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="Nuevo" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-tipoPropietario" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="tipopropietario" title="${message(code: 'tipoPropietario.tipopropietario.label', default: 'Tipo de propietario')}" />
					
						<g:sortableColumn property="estatus" title="${message(code: 'tipoPropietario.estatus.label', default: 'Estatus')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${tipoPropietarioInstanceList}" status="i" var="tipoPropietarioInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="edit" id="${tipoPropietarioInstance.id}">${fieldValue(bean: tipoPropietarioInstance, field: "tipopropietario")}</g:link></td>
					
						<td><g:formatBoolean boolean="${tipoPropietarioInstance.estatus}" true="ACTIVO" false="BAJA" />
                                                    <a href="javascript: CambiaEstatus('${tipoPropietarioInstance.id}')" title="Cambiar Estatus">
                                                        <img src="${assetPath(src: '/skin/switch.png')}" width="20" height="20"/>
                                                    </a></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${tipoPropietarioInstanceCount ?: 0}" />
			</div>
                        <script>
                            function CambiaEstatus(id){
                                var idele = document.getElementById('idele');
                                idele.value = id;
                                var frm = document.getElementById('festatus');
                                frm.submit();
                            }
                        </script>
		</div>
	</body>
</html>

grails-app/views/tipoPropietario/show.gsp
<%@ page import="siteo.administracion.catalogos.TipoPropietario" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'tipoPropietario.label', default: 'TipoPropietario')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-tipoPropietario" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="Lista" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="Nuevo" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-tipoPropietario" class="content scaffold-show" role="main">
			<h1><g:message code="Tipo de propietario" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list tipoPropietario">
			
				<g:if test="${tipoPropietarioInstance?.tipopropietario}">
				<li class="fieldcontain">
					<span id="tipopropietario-label" class="property-label"><g:message code="tipoPropietario.tipopropietario.label" default="Tipo de propietario" /></span>
					
						<span class="property-value" aria-labelledby="tipopropietario-label"><g:fieldValue bean="${tipoPropietarioInstance}" field="tipopropietario"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${tipoPropietarioInstance?.estatus}">
				<li class="fieldcontain">
					<span id="estatus-label" class="property-label"><g:message code="tipoPropietario.estatus.label" default="Estatus" /></span>
					
						<span class="property-value" aria-labelledby="estatus-label"><g:formatBoolean boolean="${tipoPropietarioInstance?.estatus}" true="ACTIVO" false="BAJA" /></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:tipoPropietarioInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${tipoPropietarioInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>